### ISSUE TITLE
[IE in Windows 7] Problem with staying on the right page

### ISSUE THREAD

**Issue by hejalsoni** [DataAnalyticsinStudentHands/CommunityHealthWorkersApp#30] opened 2015-04-20 18:45 UTC
In the "Available Classes" tab, if you click on 'info', it does not stay on the right page. It goes back the Available Classes page.

**Comment by CarlSteven** [comment] 2015-04-21 07:10
Details: I've definitely seen this error before. there are two causes. One: a JS Object being passed as a URL param in the ui-router which recently started to hiccup. Two: Something with the maps implementation causing an error upon entering the state.

Both problems have since been patched and this is unable to be reproduced for me locally nor on /CHWAppTest

Closing for now, will keep an eye out for it, if it comes back.

**Closed as completed by CarlSteven** 2015-04-21 07:10 UTC
